import type { AppNotification } from "@/src/types/notification";

const dashboardNotifications: AppNotification[] = [
  {
    id: "notif-001",
    title: "Expense report approved",
    message: "Your expense report EXP-2026-041 has been approved.",
    body: "Your expense report EXP-2026-041 for ₦45,200 has been approved by Jane Okonkwo. Reimbursement will be processed in the next payroll cycle.",
    category: "messages",
    type: "SUCCESS",
    isRead: false,
    createdAt: "2026-06-11T09:15:00Z",
    referenceId: "EXP-2026-041",
  },
  {
    id: "notif-002",
    title: "Approval required",
    message: "Payroll run PR-2026-06 needs your approval.",
    body: "Payroll run PR-2026-06 for June 2026 is ready for review. Total disbursement: ₦12,450,000 across 84 employees. Please review and approve before the cutoff on June 14.",
    category: "messages",
    type: "WARNING",
    isRead: false,
    createdAt: "2026-06-11T08:42:00Z",
    referenceId: "PR-2026-06",
  },
  {
    id: "notif-003",
    title: "Invoice payment received",
    message: "Payment of ₦2,500,000 recorded for INV-2026-118.",
    body: "A customer payment of ₦2,500,000 was recorded against invoice INV-2026-118 (Acme Industries Ltd). The invoice is now marked as paid.",
    category: "events",
    type: "SUCCESS",
    isRead: false,
    createdAt: "2026-06-10T16:30:00Z",
    referenceId: "INV-2026-118",
  },
  {
    id: "notif-004",
    title: "Budget threshold reached",
    message: "Marketing department has reached 85% of Q2 budget.",
    body: "The Marketing department has consumed 85% of its Q2 allocated budget (₦4,250,000 of ₦5,000,000). Consider reviewing upcoming spend.",
    category: "events",
    type: "WARNING",
    isRead: true,
    createdAt: "2026-06-10T11:00:00Z",
    referenceId: "BUD-MKT-Q2",
  },
  {
    id: "notif-005",
    title: "Payslip available",
    message: "Your May 2026 payslip is now available.",
    body: "Your payslip for May 2026 has been published. Net pay: ₦485,000. You can download it from the Payroll section.",
    category: "events",
    type: "INFO",
    isRead: true,
    createdAt: "2026-06-09T10:00:00Z",
  },
  {
    id: "notif-006",
    title: "Bank reconciliation failed",
    message: "Auto-reconciliation for GTBank account failed.",
    body: "Automatic bank reconciliation for GTBank Operating Account (****4521) failed due to a connection timeout. 3 transactions remain unmatched. Please reconcile manually.",
    category: "system_errors",
    type: "ERROR",
    isRead: false,
    createdAt: "2026-06-11T07:20:00Z",
    referenceId: "RECON-GTB-0611",
  },
  {
    id: "notif-007",
    title: "Webhook delivery failed",
    message: "Expense webhook to ERP returned HTTP 503.",
    body: "The expense-approved webhook to your ERP integration failed with HTTP 503 (Service Unavailable). The system will retry automatically in 15 minutes.",
    category: "system_errors",
    type: "ERROR",
    isRead: true,
    createdAt: "2026-06-08T14:55:00Z",
  },
  {
    id: "notif-008",
    title: "New comment on support ticket",
    message: "Support replied to your ticket #TKT-4421.",
    body: "A support agent has replied to your ticket #TKT-4421 regarding VAT filing configuration. Please review the response in the Support section.",
    category: "messages",
    type: "INFO",
    isRead: true,
    createdAt: "2026-06-07T09:30:00Z",
    referenceId: "TKT-4421",
  },
];

const adminNotifications: AppNotification[] = [
  {
    id: "admin-notif-001",
    title: "New company onboarded",
    message: "NovaTech Solutions completed onboarding.",
    body: "NovaTech Solutions (Plan: Enterprise) has completed onboarding with 12 users. Review their module assignments and billing setup.",
    category: "events",
    type: "SUCCESS",
    isRead: false,
    createdAt: "2026-06-11T10:00:00Z",
    referenceId: "ORG-NOVATECH",
  },
  {
    id: "admin-notif-002",
    title: "Subscription payment failed",
    message: "Payment failed for AcmeCorp Ltd subscription.",
    body: "The monthly subscription payment for AcmeCorp Ltd failed (card declined). The account will enter grace period in 3 days if unresolved.",
    category: "messages",
    type: "WARNING",
    isRead: false,
    createdAt: "2026-06-11T08:10:00Z",
    referenceId: "SUB-ACME-06",
  },
  {
    id: "admin-notif-003",
    title: "Platform health alert",
    message: "API response time exceeded 2s threshold.",
    body: "Average API response time across the platform exceeded 2 seconds for a 5-minute window. P95 latency: 2.8s. Check the Platform Health report for details.",
    category: "system_errors",
    type: "ERROR",
    isRead: false,
    createdAt: "2026-06-10T22:45:00Z",
  },
  {
    id: "admin-notif-004",
    title: "Live fix session requested",
    message: "User requested live support for ticket #TKT-8890.",
    body: "A user from Greenfield Holdings has requested a live fix session for ticket #TKT-8890 (Payroll calculation discrepancy). Session is waiting in the queue.",
    category: "messages",
    type: "INFO",
    isRead: true,
    createdAt: "2026-06-10T15:20:00Z",
    referenceId: "TKT-8890",
  },
  {
    id: "admin-notif-005",
    title: "Module update deployed",
    message: "Payroll module v2.4.1 deployed to production.",
    body: "Payroll module v2.4.1 has been deployed to production. Changes include improved tax bracket calculations and payslip PDF formatting.",
    category: "events",
    type: "INFO",
    isRead: true,
    createdAt: "2026-06-09T18:00:00Z",
  },
  {
    id: "admin-notif-006",
    title: "Integration sync error",
    message: "Slack integration webhook returned 401.",
    body: "The Slack integration for platform notifications returned HTTP 401 (Unauthorized). The OAuth token may have expired. Re-authorize in Integrations settings.",
    category: "system_errors",
    type: "ERROR",
    isRead: true,
    createdAt: "2026-06-08T11:30:00Z",
  },
];

export function getMockNotifications(scope: "dashboard" | "admin"): AppNotification[] {
  return scope === "admin" ? adminNotifications : dashboardNotifications;
}

export function getMockNotificationById(
  scope: "dashboard" | "admin",
  id: string,
): AppNotification | undefined {
  return getMockNotifications(scope).find((n) => n.id === id);
}
