"use client";

import { useState } from "react";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardDescription,
} from "@/src/components/ui/card";
import { Button } from "@/src/components/ui/button";
import { Input } from "@/src/components/ui/input";
import { Label } from "@/src/components/ui/label";
import { Switch } from "@/src/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/src/components/ui/select";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/src/components/ui/tabs";
import {
  ArrowLeft,
  Save,
  RefreshCw,
  CheckCircle,
  Settings,
  FileText,
  Lock,
  Unlock,
  Bell,
  Mail,
  Users,
  AlertCircle,
  Calculator,
  Calendar,
  Hash,
  type Icon as LucideIcon,
} from "lucide-react";
import { useRouter } from "next/navigation";

export default function JournalSettings() {
  const router = useRouter();
  const [isSaving, setIsSaving] = useState(false);
  const [saveSuccess, setSaveSuccess] = useState(false);

  // Journal Numbering Settings
  const [numberingSettings, setNumberingSettings] = useState({
    prefix: "JNL",
    suffix: "",
    includeYear: true,
    includeMonth: false,
    separator: "-",
    startingNumber: 1,
    padding: 4,
    resetAnnually: true,
    resetMonthly: false,
  });

  // Approval Settings
  const [approvalSettings, setApprovalSettings] = useState({
    requireApproval: true,
    approvalLevels: 2,
    autoApproveBelow: 100000,
    requireReview: true,
    allowSelfApproval: false,
    approverRoles: ["finance_manager", "finance_director"],
    notifyOnSubmit: true,
    notifyOnApproval: true,
    notifyOnRejection: true,
  });

  // Posting Settings
  const [postingSettings, setPostingSettings] = useState({
    allowPosting: true,
    requireApprovalBeforePost: true,
    autoPostOnApproval: false,
    allowBackdatedPosting: true,
    maxBackdatedDays: 30,
    allowFuturePosting: false,
    maxFutureDays: 7,
    preventModifyAfterPost: true,
  });

  // Default Settings
  const [defaultSettings, setDefaultSettings] = useState({
    defaultJournalType: "manual",
    defaultCurrency: "NGN",
    defaultDescription: "Journal entry",
    autoGenerateDescription: true,
    requireDescription: true,
    defaultReferencePrefix: "JE",
  });

  // Validation Settings
  const [validationSettings, setValidationSettings] = useState({
    validateBalanced: true,
    requireLineItems: true,
    minLineItems: 1,
    maxLineItems: 100,
    validateAccountExists: true,
    validateAccountType: true,
    validatePeriodOpen: true,
    validateFiscalYear: true,
    blockDuplicateReferences: true,
  });

  // Notification Settings
  const [notificationSettings, setNotificationSettings] = useState({
    emailOnSubmit: true,
    emailOnApproval: true,
    emailOnPosting: true,
    emailOnRejection: true,
    notifyCreatedBy: true,
    notifyApprovers: true,
    notifyFinanceTeam: false,
    reminderDays: 3,
  });

  const handleSave = async () => {
    setIsSaving(true);
    await new Promise((resolve) => setTimeout(resolve, 1500));
    setIsSaving(false);
    setSaveSuccess(true);
    setTimeout(() => setSaveSuccess(false), 3000);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <Button
            variant="ghost"
            onClick={() => router.back()}
            className="gap-2"
          >
            <ArrowLeft className="h-4 w-4" />
            Back
          </Button>
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight flex items-center gap-2">
              <FileText className="h-6 w-6" />
              Journal Settings
            </h1>
            <p className="text-muted-foreground mt-1">
              Configure journal entry numbering, approval workflow, and posting
              rules
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => router.refresh()}>
            <RefreshCw className="h-4 w-4 mr-2" />
            Reset
          </Button>
          <Button onClick={handleSave} disabled={isSaving}>
            {isSaving ? (
              <>
                <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                Saving...
              </>
            ) : (
              <>
                <Save className="mr-2 h-4 w-4" />
                Save Settings
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Success Message */}
      {saveSuccess && (
        <Card className="border-green-200 bg-green-50">
          <CardContent className="p-4">
            <div className="flex items-center gap-2 text-green-700">
              <CheckCircle className="h-5 w-5" />
              <span>Journal settings saved successfully!</span>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Settings Tabs */}
      <Tabs defaultValue="numbering" className="w-full">
        <TabsList className="grid w-full grid-cols-6">
          <TabsTrigger value="numbering">Numbering</TabsTrigger>
          <TabsTrigger value="approval">Approval</TabsTrigger>
          <TabsTrigger value="posting">Posting</TabsTrigger>
          <TabsTrigger value="defaults">Defaults</TabsTrigger>
          <TabsTrigger value="validation">Validation</TabsTrigger>
          <TabsTrigger value="notifications">Notifications</TabsTrigger>
        </TabsList>

        {/* Journal Numbering Tab */}
        <TabsContent value="numbering" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <CardTitle>Journal Numbering</CardTitle>
              <CardDescription>
                Configure how journal entries are numbered
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label>Prefix</Label>
                  <Input
                    value={numberingSettings.prefix}
                    onChange={(e) =>
                      setNumberingSettings((prev) => ({
                        ...prev,
                        prefix: e.target.value,
                      }))
                    }
                    className="mt-1 font-mono"
                    placeholder="JNL"
                  />
                </div>
                <div>
                  <Label>Suffix</Label>
                  <Input
                    value={numberingSettings.suffix}
                    onChange={(e) =>
                      setNumberingSettings((prev) => ({
                        ...prev,
                        suffix: e.target.value,
                      }))
                    }
                    className="mt-1 font-mono"
                    placeholder="Optional"
                  />
                </div>
                <div>
                  <Label>Separator</Label>
                  <Input
                    value={numberingSettings.separator}
                    onChange={(e) =>
                      setNumberingSettings((prev) => ({
                        ...prev,
                        separator: e.target.value,
                      }))
                    }
                    className="mt-1 font-mono"
                    placeholder="-"
                    maxLength={1}
                  />
                </div>
                <div>
                  <Label>Starting Number</Label>
                  <Input
                    type="number"
                    value={numberingSettings.startingNumber}
                    onChange={(e) =>
                      setNumberingSettings((prev) => ({
                        ...prev,
                        startingNumber: parseInt(e.target.value) || 1,
                      }))
                    }
                    className="mt-1"
                  />
                </div>
                <div>
                  <Label>Number Padding</Label>
                  <Select
                    value={numberingSettings.padding.toString()}
                    onValueChange={(v) =>
                      setNumberingSettings((prev) => ({
                        ...prev,
                        padding: parseInt(v),
                      }))
                    }
                  >
                    <SelectTrigger className="mt-1">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="3">3 digits (001)</SelectItem>
                      <SelectItem value="4">4 digits (0001)</SelectItem>
                      <SelectItem value="5">5 digits (00001)</SelectItem>
                      <SelectItem value="6">6 digits (000001)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="border-t pt-4">
                <h3 className="font-semibold mb-3">Include in Number</h3>
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Include Year</Label>
                      <p className="text-xs text-muted-foreground">
                        Add current year to journal number (e.g., JNL-2026-0001)
                      </p>
                    </div>
                    <Switch
                      checked={numberingSettings.includeYear}
                      onCheckedChange={(checked) =>
                        setNumberingSettings((prev) => ({
                          ...prev,
                          includeYear: checked,
                        }))
                      }
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Include Month</Label>
                      <p className="text-xs text-muted-foreground">
                        Add current month to journal number (e.g.,
                        JNL-2026-03-0001)
                      </p>
                    </div>
                    <Switch
                      checked={numberingSettings.includeMonth}
                      onCheckedChange={(checked) =>
                        setNumberingSettings((prev) => ({
                          ...prev,
                          includeMonth: checked,
                        }))
                      }
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Reset Number Annually</Label>
                      <p className="text-xs text-muted-foreground">
                        Start numbering from 1 at the beginning of each fiscal
                        year
                      </p>
                    </div>
                    <Switch
                      checked={numberingSettings.resetAnnually}
                      onCheckedChange={(checked) =>
                        setNumberingSettings((prev) => ({
                          ...prev,
                          resetAnnually: checked,
                        }))
                      }
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Reset Number Monthly</Label>
                      <p className="text-xs text-muted-foreground">
                        Start numbering from 1 at the beginning of each month
                      </p>
                    </div>
                    <Switch
                      checked={numberingSettings.resetMonthly}
                      onCheckedChange={(checked) =>
                        setNumberingSettings((prev) => ({
                          ...prev,
                          resetMonthly: checked,
                        }))
                      }
                    />
                  </div>
                </div>
              </div>

              <div className="p-3 bg-muted rounded-lg">
                <p className="text-sm font-medium">Preview</p>
                <p className="text-xs text-muted-foreground mt-1 font-mono">
                  {numberingSettings.prefix}
                  {numberingSettings.includeYear &&
                    `${numberingSettings.separator}2026`}
                  {numberingSettings.includeMonth &&
                    `${numberingSettings.separator}03`}
                  {numberingSettings.separator}
                  {numberingSettings.startingNumber
                    .toString()
                    .padStart(numberingSettings.padding, "0")}
                  {numberingSettings.suffix &&
                    `${numberingSettings.separator}${numberingSettings.suffix}`}
                </p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Approval Settings Tab */}
        <TabsContent value="approval" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <CardTitle>Approval Workflow</CardTitle>
              <CardDescription>
                Configure journal entry approval requirements
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <Label>Require Approval</Label>
                  <p className="text-xs text-muted-foreground">
                    Journal entries must be approved before posting
                  </p>
                </div>
                <Switch
                  checked={approvalSettings.requireApproval}
                  onCheckedChange={(checked) =>
                    setApprovalSettings((prev) => ({
                      ...prev,
                      requireApproval: checked,
                    }))
                  }
                />
              </div>

              {approvalSettings.requireApproval && (
                <>
                  <div className="border-t pt-4">
                    <Label>Number of Approval Levels</Label>
                    <Select
                      value={approvalSettings.approvalLevels.toString()}
                      onValueChange={(v) =>
                        setApprovalSettings((prev) => ({
                          ...prev,
                          approvalLevels: parseInt(v),
                        }))
                      }
                    >
                      <SelectTrigger className="mt-1">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="1">
                          1 Level (Single Approver)
                        </SelectItem>
                        <SelectItem value="2">
                          2 Levels (Manager + Director)
                        </SelectItem>
                        <SelectItem value="3">
                          3 Levels (Manager + Director + VP)
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label>Auto-approve Amount Threshold</Label>
                    <div className="relative mt-1">
                      <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">
                        ₦
                      </span>
                      <Input
                        type="number"
                        value={approvalSettings.autoApproveBelow}
                        onChange={(e) =>
                          setApprovalSettings((prev) => ({
                            ...prev,
                            autoApproveBelow: parseInt(e.target.value) || 0,
                          }))
                        }
                        className="pl-7"
                      />
                    </div>
                    <p className="text-xs text-muted-foreground mt-1">
                      Journal entries below this amount are auto-approved
                    </p>
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Require Review</Label>
                      <p className="text-xs text-muted-foreground">
                        Additional review required for high-value entries
                      </p>
                    </div>
                    <Switch
                      checked={approvalSettings.requireReview}
                      onCheckedChange={(checked) =>
                        setApprovalSettings((prev) => ({
                          ...prev,
                          requireReview: checked,
                        }))
                      }
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Allow Self-Approval</Label>
                      <p className="text-xs text-muted-foreground">
                        Allow users to approve their own journal entries
                      </p>
                    </div>
                    <Switch
                      checked={approvalSettings.allowSelfApproval}
                      onCheckedChange={(checked) =>
                        setApprovalSettings((prev) => ({
                          ...prev,
                          allowSelfApproval: checked,
                        }))
                      }
                    />
                  </div>
                </>
              )}

              <div className="border-t pt-4">
                <h3 className="font-semibold mb-3">Notifications</h3>
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Label>Notify on Submit</Label>
                    <Switch
                      checked={approvalSettings.notifyOnSubmit}
                      onCheckedChange={(checked) =>
                        setApprovalSettings((prev) => ({
                          ...prev,
                          notifyOnSubmit: checked,
                        }))
                      }
                    />
                  </div>
                  <div className="flex items-center justify-between">
                    <Label>Notify on Approval</Label>
                    <Switch
                      checked={approvalSettings.notifyOnApproval}
                      onCheckedChange={(checked) =>
                        setApprovalSettings((prev) => ({
                          ...prev,
                          notifyOnApproval: checked,
                        }))
                      }
                    />
                  </div>
                  <div className="flex items-center justify-between">
                    <Label>Notify on Rejection</Label>
                    <Switch
                      checked={approvalSettings.notifyOnRejection}
                      onCheckedChange={(checked) =>
                        setApprovalSettings((prev) => ({
                          ...prev,
                          notifyOnRejection: checked,
                        }))
                      }
                    />
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Posting Settings Tab */}
        <TabsContent value="posting" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <CardTitle>Posting Rules</CardTitle>
              <CardDescription>
                Configure how journal entries are posted to the ledger
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <Label>Allow Posting</Label>
                  <p className="text-xs text-muted-foreground">
                    Enable posting of journal entries to general ledger
                  </p>
                </div>
                <Switch
                  checked={postingSettings.allowPosting}
                  onCheckedChange={(checked) =>
                    setPostingSettings((prev) => ({
                      ...prev,
                      allowPosting: checked,
                    }))
                  }
                />
              </div>

              {postingSettings.allowPosting && (
                <>
                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Require Approval Before Posting</Label>
                      <p className="text-xs text-muted-foreground">
                        Journal entries must be approved before posting
                      </p>
                    </div>
                    <Switch
                      checked={postingSettings.requireApprovalBeforePost}
                      onCheckedChange={(checked) =>
                        setPostingSettings((prev) => ({
                          ...prev,
                          requireApprovalBeforePost: checked,
                        }))
                      }
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Auto-post on Approval</Label>
                      <p className="text-xs text-muted-foreground">
                        Automatically post journal entries when approved
                      </p>
                    </div>
                    <Switch
                      checked={postingSettings.autoPostOnApproval}
                      onCheckedChange={(checked) =>
                        setPostingSettings((prev) => ({
                          ...prev,
                          autoPostOnApproval: checked,
                        }))
                      }
                    />
                  </div>

                  <div className="border-t pt-4">
                    <h3 className="font-semibold mb-3">
                      Backdating & Future Dating
                    </h3>

                    <div className="flex items-center justify-between mb-3">
                      <div>
                        <Label>Allow Backdated Posting</Label>
                        <p className="text-xs text-muted-foreground">
                          Allow posting of journal entries with past dates
                        </p>
                      </div>
                      <Switch
                        checked={postingSettings.allowBackdatedPosting}
                        onCheckedChange={(checked) =>
                          setPostingSettings((prev) => ({
                            ...prev,
                            allowBackdatedPosting: checked,
                          }))
                        }
                      />
                    </div>

                    {postingSettings.allowBackdatedPosting && (
                      <div className="ml-6">
                        <Label>Maximum Backdated Days</Label>
                        <Input
                          type="number"
                          value={postingSettings.maxBackdatedDays}
                          onChange={(e) =>
                            setPostingSettings((prev) => ({
                              ...prev,
                              maxBackdatedDays: parseInt(e.target.value) || 30,
                            }))
                          }
                          className="mt-1"
                        />
                        <p className="text-xs text-muted-foreground mt-1">
                          Maximum days in the past allowed for posting
                        </p>
                      </div>
                    )}

                    <div className="flex items-center justify-between mt-3">
                      <div>
                        <Label>Allow Future Posting</Label>
                        <p className="text-xs text-muted-foreground">
                          Allow posting of journal entries with future dates
                        </p>
                      </div>
                      <Switch
                        checked={postingSettings.allowFuturePosting}
                        onCheckedChange={(checked) =>
                          setPostingSettings((prev) => ({
                            ...prev,
                            allowFuturePosting: checked,
                          }))
                        }
                      />
                    </div>

                    {postingSettings.allowFuturePosting && (
                      <div className="ml-6">
                        <Label>Maximum Future Days</Label>
                        <Input
                          type="number"
                          value={postingSettings.maxFutureDays}
                          onChange={(e) =>
                            setPostingSettings((prev) => ({
                              ...prev,
                              maxFutureDays: parseInt(e.target.value) || 7,
                            }))
                          }
                          className="mt-1"
                        />
                      </div>
                    )}
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Prevent Modification After Posting</Label>
                      <p className="text-xs text-muted-foreground">
                        Lock journal entries after they are posted
                      </p>
                    </div>
                    <Switch
                      checked={postingSettings.preventModifyAfterPost}
                      onCheckedChange={(checked) =>
                        setPostingSettings((prev) => ({
                          ...prev,
                          preventModifyAfterPost: checked,
                        }))
                      }
                    />
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Default Settings Tab */}
        <TabsContent value="defaults" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <CardTitle>Default Values</CardTitle>
              <CardDescription>
                Set default values for new journal entries
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label>Default Journal Type</Label>
                  <Select
                    value={defaultSettings.defaultJournalType}
                    onValueChange={(value) =>
                      setDefaultSettings((prev) => ({
                        ...prev,
                        defaultJournalType: value,
                      }))
                    }
                  >
                    <SelectTrigger className="mt-1">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="manual">Manual Entry</SelectItem>
                      <SelectItem value="system">System Generated</SelectItem>
                      <SelectItem value="recurring">Recurring</SelectItem>
                      <SelectItem value="adjustment">Adjustment</SelectItem>
                      <SelectItem value="closing">Closing Entry</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label>Default Currency</Label>
                  <Select
                    value={defaultSettings.defaultCurrency}
                    onValueChange={(value) =>
                      setDefaultSettings((prev) => ({
                        ...prev,
                        defaultCurrency: value,
                      }))
                    }
                  >
                    <SelectTrigger className="mt-1">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="NGN">Nigerian Naira (NGN)</SelectItem>
                      <SelectItem value="USD">US Dollar (USD)</SelectItem>
                      <SelectItem value="EUR">Euro (EUR)</SelectItem>
                      <SelectItem value="GBP">British Pound (GBP)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label>Default Reference Prefix</Label>
                  <Input
                    value={defaultSettings.defaultReferencePrefix}
                    onChange={(e) =>
                      setDefaultSettings((prev) => ({
                        ...prev,
                        defaultReferencePrefix: e.target.value,
                      }))
                    }
                    className="mt-1 font-mono"
                    placeholder="JE"
                  />
                </div>
              </div>

              <div className="border-t pt-4">
                <h3 className="font-semibold mb-3">Description Settings</h3>

                <div className="flex items-center justify-between mb-3">
                  <div>
                    <Label>Auto-generate Description</Label>
                    <p className="text-xs text-muted-foreground">
                      Automatically generate description based on line items
                    </p>
                  </div>
                  <Switch
                    checked={defaultSettings.autoGenerateDescription}
                    onCheckedChange={(checked) =>
                      setDefaultSettings((prev) => ({
                        ...prev,
                        autoGenerateDescription: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Require Description</Label>
                    <p className="text-xs text-muted-foreground">
                      Make description field mandatory for all journal entries
                    </p>
                  </div>
                  <Switch
                    checked={defaultSettings.requireDescription}
                    onCheckedChange={(checked) =>
                      setDefaultSettings((prev) => ({
                        ...prev,
                        requireDescription: checked,
                      }))
                    }
                  />
                </div>

                {defaultSettings.autoGenerateDescription && (
                  <div className="p-3 bg-muted rounded-lg mt-3">
                    <p className="text-sm font-medium">Preview</p>
                    <p className="text-xs text-muted-foreground mt-1">
                      {defaultSettings.defaultDescription} (from sales invoice,
                      etc.)
                    </p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Validation Settings Tab */}
        <TabsContent value="validation" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <CardTitle>Validation Rules</CardTitle>
              <CardDescription>
                Configure validation rules for journal entries
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <Label>Validate Balanced Entries</Label>
                    <p className="text-xs text-muted-foreground">
                      Ensure debits equal credits before saving
                    </p>
                  </div>
                  <Switch
                    checked={validationSettings.validateBalanced}
                    onCheckedChange={(checked) =>
                      setValidationSettings((prev) => ({
                        ...prev,
                        validateBalanced: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Require Line Items</Label>
                    <p className="text-xs text-muted-foreground">
                      At least one line item is required per journal entry
                    </p>
                  </div>
                  <Switch
                    checked={validationSettings.requireLineItems}
                    onCheckedChange={(checked) =>
                      setValidationSettings((prev) => ({
                        ...prev,
                        requireLineItems: checked,
                      }))
                    }
                  />
                </div>

                {validationSettings.requireLineItems && (
                  <div className="ml-6 grid grid-cols-2 gap-4">
                    <div>
                      <Label>Min Line Items</Label>
                      <Input
                        type="number"
                        value={validationSettings.minLineItems}
                        onChange={(e) =>
                          setValidationSettings((prev) => ({
                            ...prev,
                            minLineItems: parseInt(e.target.value) || 1,
                          }))
                        }
                        className="mt-1"
                      />
                    </div>
                    <div>
                      <Label>Max Line Items</Label>
                      <Input
                        type="number"
                        value={validationSettings.maxLineItems}
                        onChange={(e) =>
                          setValidationSettings((prev) => ({
                            ...prev,
                            maxLineItems: parseInt(e.target.value) || 100,
                          }))
                        }
                        className="mt-1"
                      />
                    </div>
                  </div>
                )}

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Validate Account Exists</Label>
                    <p className="text-xs text-muted-foreground">
                      Verify that accounts exist in the chart of accounts
                    </p>
                  </div>
                  <Switch
                    checked={validationSettings.validateAccountExists}
                    onCheckedChange={(checked) =>
                      setValidationSettings((prev) => ({
                        ...prev,
                        validateAccountExists: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Validate Account Type</Label>
                    <p className="text-xs text-muted-foreground">
                      Ensure account types match normal balance rules
                    </p>
                  </div>
                  <Switch
                    checked={validationSettings.validateAccountType}
                    onCheckedChange={(checked) =>
                      setValidationSettings((prev) => ({
                        ...prev,
                        validateAccountType: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Validate Period Open</Label>
                    <p className="text-xs text-muted-foreground">
                      Prevent posting to closed accounting periods
                    </p>
                  </div>
                  <Switch
                    checked={validationSettings.validatePeriodOpen}
                    onCheckedChange={(checked) =>
                      setValidationSettings((prev) => ({
                        ...prev,
                        validatePeriodOpen: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Validate Fiscal Year</Label>
                    <p className="text-xs text-muted-foreground">
                      Prevent posting to closed fiscal years
                    </p>
                  </div>
                  <Switch
                    checked={validationSettings.validateFiscalYear}
                    onCheckedChange={(checked) =>
                      setValidationSettings((prev) => ({
                        ...prev,
                        validateFiscalYear: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Block Duplicate References</Label>
                    <p className="text-xs text-muted-foreground">
                      Prevent duplicate reference numbers
                    </p>
                  </div>
                  <Switch
                    checked={validationSettings.blockDuplicateReferences}
                    onCheckedChange={(checked) =>
                      setValidationSettings((prev) => ({
                        ...prev,
                        blockDuplicateReferences: checked,
                      }))
                    }
                  />
                </div>
              </div>

              <div className="p-3 bg-blue-50 rounded-lg mt-4">
                <div className="flex items-start gap-2">
                  <AlertCircle className="h-4 w-4 text-blue-600 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-blue-800">
                      Validation Impact
                    </p>
                    <p className="text-xs text-blue-700 mt-1">
                      These validation rules help maintain data integrity and
                      prevent accounting errors. Users will be notified when
                      validation rules are violated.
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Notification Settings Tab */}
        <TabsContent value="notifications" className="space-y-4 mt-4">
          <Card>
            <CardHeader>
              <CardTitle>Email Notifications</CardTitle>
              <CardDescription>
                Configure who receives notifications and when
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <Label>Email on Submit</Label>
                    <p className="text-xs text-muted-foreground">
                      Send email when journal entry is submitted
                    </p>
                  </div>
                  <Switch
                    checked={notificationSettings.emailOnSubmit}
                    onCheckedChange={(checked) =>
                      setNotificationSettings((prev) => ({
                        ...prev,
                        emailOnSubmit: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Email on Approval</Label>
                    <p className="text-xs text-muted-foreground">
                      Send email when journal entry is approved
                    </p>
                  </div>
                  <Switch
                    checked={notificationSettings.emailOnApproval}
                    onCheckedChange={(checked) =>
                      setNotificationSettings((prev) => ({
                        ...prev,
                        emailOnApproval: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Email on Posting</Label>
                    <p className="text-xs text-muted-foreground">
                      Send email when journal entry is posted
                    </p>
                  </div>
                  <Switch
                    checked={notificationSettings.emailOnPosting}
                    onCheckedChange={(checked) =>
                      setNotificationSettings((prev) => ({
                        ...prev,
                        emailOnPosting: checked,
                      }))
                    }
                  />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label>Email on Rejection</Label>
                    <p className="text-xs text-muted-foreground">
                      Send email when journal entry is rejected
                    </p>
                  </div>
                  <Switch
                    checked={notificationSettings.emailOnRejection}
                    onCheckedChange={(checked) =>
                      setNotificationSettings((prev) => ({
                        ...prev,
                        emailOnRejection: checked,
                      }))
                    }
                  />
                </div>
              </div>

              <div className="border-t pt-4">
                <h3 className="font-semibold mb-3">Recipients</h3>
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Notify Created By</Label>
                      <p className="text-xs text-muted-foreground">
                        Send notifications to the person who created the entry
                      </p>
                    </div>
                    <Switch
                      checked={notificationSettings.notifyCreatedBy}
                      onCheckedChange={(checked) =>
                        setNotificationSettings((prev) => ({
                          ...prev,
                          notifyCreatedBy: checked,
                        }))
                      }
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Notify Approvers</Label>
                      <p className="text-xs text-muted-foreground">
                        Send notifications to approval chain
                      </p>
                    </div>
                    <Switch
                      checked={notificationSettings.notifyApprovers}
                      onCheckedChange={(checked) =>
                        setNotificationSettings((prev) => ({
                          ...prev,
                          notifyApprovers: checked,
                        }))
                      }
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    <div>
                      <Label>Notify Finance Team</Label>
                      <p className="text-xs text-muted-foreground">
                        Send notifications to finance department
                      </p>
                    </div>
                    <Switch
                      checked={notificationSettings.notifyFinanceTeam}
                      onCheckedChange={(checked) =>
                        setNotificationSettings((prev) => ({
                          ...prev,
                          notifyFinanceTeam: checked,
                        }))
                      }
                    />
                  </div>

                  <div>
                    <Label>Reminder Days</Label>
                    <Input
                      type="number"
                      value={notificationSettings.reminderDays}
                      onChange={(e) =>
                        setNotificationSettings((prev) => ({
                          ...prev,
                          reminderDays: parseInt(e.target.value) || 3,
                        }))
                      }
                      className="mt-1"
                    />
                    <p className="text-xs text-muted-foreground mt-1">
                      Days before due date to send reminders for pending
                      approvals
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
